### ISSUE TITLE
CLI upload error message when user is not logged in

### ISSUE THREAD

**Issue by DanNBullock** [brainlife/brainlife#179]
Currently when a user is not logged into brainlife when using the CLI upload commands, the following error message(s) are returned:

`node:4125365) UnhandledPromiseRejectionWarning: StatusCodeError: 500 - {"message":"not member of the group you have specified"}
    at new StatusCodeError (/usr/local/lib/node_modules/brainlife/node_modules/request-promise-core/lib/errors.js:32:15)
    at Request.plumbing.callback (/usr/local/lib/node_modules/brainlife/node_modules/request-promise-core/lib/plumbing.js:104:33)
    at Request.RP$callback [as _callback] (/usr/local/lib/node_modules/brainlife/node_modules/request-promise-core/lib/plumbing.js:46:31)
    at Request.self.callback (/usr/local/lib/node_modules/brainlife/node_modules/request/request.js:185:22)
    at Request.emit (events.js:314:20)
    at Request.<anonymous> (/usr/local/lib/node_modules/brainlife/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:314:20)
    at IncomingMessage.<anonymous> (/usr/local/lib/node_modules/brainlife/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:420:28)
    at IncomingMessage.emit (events.js:326:22)
(node:4125365) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4125365) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:4125365) UnhandledPromiseRejectionWarning: not member of the group you have specified
(node:4125365) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https(base) dan@heilbronnerPC02:/media/dan/deepData/data/NHP_DICO(base) dan@heilbronnerPC02:/media/dan/deepData/d(base) dan@heil(base) da(ba(base) da(base) dan@heilbronnerPC02:(base) dan@heilbronnerPC02:(ba`

This error message may not appropriately delineate between cases in which the user is not genuinely a member of the targeted projected, and cases in which the user is simply not logged in appropriately.  

Command used:  bl bids upload

**Comment by anibalsolon** [comment]
Good one- working in a similar issue right now, will address this too.
